PackageName: entity
IsAllDataBase: true
TableName: dict
SaveFileName: dictModel
#SaveFilePwd: "D:\\tempcode\\" #绝对路径方式
SaveFilePwd: './entity/' #相对路径方式
SqlConfig:
  Type: mysql # 数据库类型
  Host: rm-2ze1gfhk0hmq7l3ov.mysql.rds.aliyuncs.com # 填写你的数据库账号
  Port: 3306 # 端口号
  Account: youth_mall # 账号
  Password: A8Zh_7pQG_eaiLD-pWLc77t #密码
  DataBaseName: crmeb # 数据库名称
